# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: S.C. Allemang
email: samuel.allemang@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  S.C. Allemang is a front-end web dev, charity co-founder (TXDL.ca), and all-around creative genius (Lunchmeat, anyone?!).
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://scallemang.ca" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  scallemang

# Build settings
markdown: kramdown
exclude: [gulpfile.js, package.json, node_modules, bower.json, bower_components]
